const reportController = require("../controllers/reportController");

const { Router } = require("express");
const { authMiddleware } = require("../middleware/auth.middleware");
const upload = require("../config/confi.multer");

const interviewReportRouter = Router();

/********************
 * @route POST /api/interviewreport/generate
 * @desc Generate an interview report based on the provided resume, self-description, job title, and job description.
 * @access Private
 ********************/
interviewReportRouter.post(
  "/generate",
  authMiddleware,
  upload.single("resume"),
  reportController.generateReport,
);
/**
 * @route GET /api/interviewreport/myreports
 * @desc Get all interview reports generated by the currently logged-in user.
 * @access Private
 */

interviewReportRouter.get(
  "/myreports",
  authMiddleware,
  reportController.getreportByUserId,
);

module.exports = interviewReportRouter;
